name: tix_analytics
description: A new flutter module project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry: ^8.14.1
  device_info: ^2.0.0
  firebase_analytics: ^10.0.6
  mixpanel_flutter: ^2.3.4
  facebook_app_events: ^0.19.6
  http: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.tix_analytics
    iosBundleIdentifier: com.example.tixAnalytics
