name: tix_analytics
description: A new flutter module project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry: ^6.6.1
  device_info: ^2.0.3
  firebase_analytics: ^9.1.12


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.tix_analytics
    iosBundleIdentifier: com.example.tixAnalytics
