name: tix_analytics
description: A new flutter module project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry: ^6.22.0
  device_info: ^2.0.0
  firebase_analytics: ^10.0.6
  flutuate_mixpanel: ^1.1.8
  facebook_app_events:
    git:
      url : https://github.com/AsUnDeRz/flutter_facebook_app_events.git
      ref : master


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.tix_analytics
    iosBundleIdentifier: com.example.tixAnalytics
